
[pyrogram]
api_id = 22359038                                                      # required
api_hash = "b3901895dc193c30c808ba4f1b550ed0"                       # required
bot_token = "7196443239:AAFLFmiywWXoXoz61eSF9m34xj31hqxIJ00"                  # either bot_token or session_string is required
session_string = "" # either bot_token or session_string is required
sudo_users = [5531461861]                                 # optional


# All chats must be in the format of [-]1001234567890
# Atleast one chat must be added

[[chats]]
from = -1002200660173        # required
to = -1002217171960             # required
