
[pyrogram]
api_id = 2018347                                                      # required
api_hash = "049573814bd3a7b1141bed18011fc6"                       # required
bot_token = "6752230007:AAGtbsdCfcu184hsYqA13ipjmq-5ULg"                  # either bot_token or session_string is required
session_string = "" # either bot_token or session_string is required
sudo_users = [5050588448]                                 # optional


# All chats must be in the format of [-]1001234567890
# Atleast one chat must be added

[[chats]]
from = -1001989382228        # required
to = -1002026461119             # required
